services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:8080